# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'draft_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(667, 803)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imagePath = QtWidgets.QLabel(self.centralwidget)
        self.imagePath.setGeometry(QtCore.QRect(170, 18, 461, 41))
        self.imagePath.setFrameShape(QtWidgets.QFrame.Panel)
        self.imagePath.setText("")
        self.imagePath.setObjectName("imagePath")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 480, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.cameraArea = QtWidgets.QLabel(self.centralwidget)
        self.cameraArea.setGeometry(QtCore.QRect(30, 90, 600, 360))
        self.cameraArea.setFrameShape(QtWidgets.QFrame.Box)
        self.cameraArea.setText("")
        self.cameraArea.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraArea.setObjectName("cameraArea")
        self.resultArea = QtWidgets.QLabel(self.centralwidget)
        self.resultArea.setGeometry(QtCore.QRect(30, 540, 591, 131))
        self.resultArea.setFrameShape(QtWidgets.QFrame.Box)
        self.resultArea.setText("")
        self.resultArea.setObjectName("resultArea")
        self.startReading = QtWidgets.QPushButton(self.centralwidget)
        self.startReading.setGeometry(QtCore.QRect(100, 690, 201, 51))
        self.startReading.setObjectName("startReading")
        self.stopReading = QtWidgets.QPushButton(self.centralwidget)
        self.stopReading.setGeometry(QtCore.QRect(340, 690, 201, 51))
        self.stopReading.setObjectName("stopReading")
        self.imageBtn = QtWidgets.QPushButton(self.centralwidget)
        self.imageBtn.setGeometry(QtCore.QRect(30, 18, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.imageBtn.setFont(font)
        self.imageBtn.setObjectName("imageBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 667, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Result"))
        self.startReading.setText(_translate("MainWindow", "Start Reading"))
        self.stopReading.setText(_translate("MainWindow", "Stop Reading"))
        self.imageBtn.setText(_translate("MainWindow", "Image"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
